taskapp/urls.py
from django.urls import path
from .views import *


app_name="taskapp"
urlpatterns=[
path("",HomeView.as_view()),
path("nepal/",NepalView.as_view()),
path("about/",AboutView.as_view()),
path("task/list/",TaskListView.as_view()),
path("blog/list/",BlogListView.as_view()),
path("bottle/list/",BottleListView.as_view()),
path("task/<int:pk>/detail/",TaskDetailView.as_view(),name="taskdetail"),
path("blog/<int:pk>/detail/",BlogDetailView.as_view()),
path("task/add/",TaskAddView.as_view()),
path("blog/add/",BlogAddView.as_view()),
path("bottle/add/",BottleAddView.as_view()),
path("task/<int:pk>/update/",TaskUpdateView.as_view()),
path("blog/<int:pk>/update/",BlogUpdateView.as_view()),
path("task/<int:pk>/delete/",TaskDeleteView.as_view()),
path("blog/<int:pk>/delete/",BlogDeleteView.as_view()),

path("login/",LoginView.as_view(),name="login"),
path("signup/",SignupView.as_view(),name="signup"),
path("logout/",LogoutView.as_view(),name="logout"),
]

taskproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("taskapp.urls")),

]

taskapp/models.py
from django.db import models
from django.contrib.auth.models import User



class Task(models.Model):
	title=models.CharField(max_length=500)
	description=models.TextField()
	created_on=models.DateTimeField(auto_now_add=True)
	due_date=models.DateTimeField()
	given_to=models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.title



class Blog(models.Model):
	title=models.CharField(max_length=500)
	description=models.TextField()
	author=models.CharField(max_length=50)
	published_on=models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.title



class Bottle(models.Model):
	bottle_type=models.CharField(max_length=50)
	color=models.CharField(max_length=49)
	capacity_in_ml=models.PositiveIntegerField()
	height_in_cm=models.PositiveIntegerField()
	company=models.CharField(max_length=50)

	def __str__(self):
		return self.bottle_type+"("+self.color+")"

taskapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User




class TaskForm(forms.ModelForm):
	class Meta:
		model=Task
		fields=["title","description","due_date","given_to"]   #fields="__all__"



class BlogForm(forms.ModelForm):
	class Meta:
		model=Blog
		fields="__all__"



class BottleForm(forms.ModelForm):
	class Meta:
		model=Bottle
		fields="__all__"




class LoginForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Username"
		}))
	password=forms.CharField(widget=forms.PasswordInput(attrs={
		'class':"form-control",
		"autocomplete":"off",
		"placeholder":"Enter password"
		}))





class SignupForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Username"
		}))
	email=forms.EmailField(widget=forms.EmailInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter email"
		}))
	password=forms.CharField(widget=forms.PasswordInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Password"
		}))
	confirm_password=forms.CharField(widget=forms.PasswordInput(attrs={
		"class":"form-control",
		"autocomplete":"off",
		"placeholder":"Enter Password"
		}))


	def clean_username(self):
		uname=self.cleaned_data['username']
		if User.objects.filter(username=uname).exists():
			raise forms.ValidationError("Username is already exist")

		
		return uname



	def clean_confirm_password(self):
		pw=self.cleaned_data['password']
		c_pw=self.cleaned_data['confirm_password']
		if (pw !=c_pw):
			raise forms.ValidationError("Password did not match.")

		return c_pw

taskapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import *
from .models import *
from .forms import *
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse,reverse_lazy

# Create your views here.
class HomeView(TemplateView):
	template_name="index.html"

	def dispatch(self,request,*args,**kwargs):
		if request.user.is_authenticated:
			pass
		else:
			return redirect("taskapp:login")


		return super().dispatch(request,*args,**kwargs)

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		context["alltasks"]=Task.objects.all()
		return context


class NepalView(TemplateView):
	template_name="nepal.html"

class AboutView(TemplateView):
	template_name="about.html"


class TaskListView(ListView):
	template_name="tasks.html"
	queryset=Task.objects.all().order_by("-id")  #queryset API
	context_object_name="alltasks"


class BlogListView(ListView):
	template_name="blog.html"
	queryset=Blog.objects.all().order_by("-id")
	context_object_name="allblogs"



class BottleListView(ListView):
	template_name="bottle.html"
	queryset=Bottle.objects.all().order_by("-id")
	context_object_name="allbottles"


class TaskDetailView(DetailView):
	template_name="taskdetail.html"
	queryset=Task.objects.all()     #model=Task
	context_object_name="taskobject"



class BlogDetailView(DetailView):
	template_name="blogdetail.html"
	queryset=Blog.objects.all()     #model=Blog
	context_object_name="blogobject"


class TaskAddView(CreateView):
	template_name="taskcreate.html"
	form_class=TaskForm
	success_url="/"




class BlogAddView(CreateView):
	template_name="blogcreate.html"
	form_class=BlogForm
	success_url="/"


class BottleAddView(CreateView):
	template_name="bottlecreate.html"
	form_class=BottleForm
	success_url="/"

class TaskUpdateView(UpdateView):
	template_name="taskcreate.html"
	form_class=TaskForm
	success_url="/task/list/"
	model=Task
	queryset=Task.objects.all()    #[optional with model]



class BlogUpdateView(UpdateView):
	template_name="blogcreate.html"
	form_class=BlogForm
	success_url="/blog/list/"
	model=Blog
	queryset=Blog.objects.all()    #[optional with model]




class TaskDeleteView(DeleteView):
	template_name="taskdelete.html"
	model=Task
	success_url="/task/list/"



class BlogDeleteView(DeleteView):
	template_name="blogdelete.html"
	model=Blog
	success_url="/blog/list/"




class LoginView(FormView):
	template_name="login.html"
	form_class=LoginForm
	success_url="/"


	def form_valid(self,form):
		x=form.cleaned_data["username"]
		y=form.cleaned_data["password"]
		usr=authenticate(username=x,password=y)
		if usr is not None:
			login(self.request,usr)

		else:
			return render(self.request,'login.html',
				{
				"error":"Invalid Credential",
				"form":form
				})

		return super().form_valid(form)

	def get_success_url(self):


		if self.request.user.is_superuser:
			return "/"

		else:
			return '/'


class SignupView(FormView):
	template_name="signup.html"
	form_class=SignupForm
	success_url="/"


	def form_valid(self,form):
		x=form.cleaned_data["username"]
		e=form.cleaned_data["email"]
		y=form.cleaned_data["password"]

		usr=User.objects.create_user(x,e,y)
		login(self.request,usr)


		return super().form_valid(form)



class LogoutView(View):
	def get(self,request):
		logout(request)
		
		return redirect('/')

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>hello</title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
	<a href="/">Home</a> |
	<a href="/nepal/">Nepal</a> |
	<a href="/about/">About</a> |
	<a href="/task/list/">Tasks</a> |
	<a href="/blog/list/">Blogs</a> |
	<a href="/bottle/list/">Bottles</a>|
	{% if request.user.is_authenticated %}
	<a href="#">{{request.user}}</a>-
	<a href="{% url 'taskapp:logout' %}">Logout</a>|
	{% else %}
	<a href="{% url 'taskapp:login' %}">Login</a>|
	{% endif %}
	<a href="{% url 'taskapp:signup' %}">Sign UP</a>|
	<hr>

	{% block content %}
	{% endblock %}
</body>
</html>

templates/blogcreate.html
{% extends "base.html" %}
{% block content %}


<h3>Blog Form</h3><hr>
<form method="POST" action="">
	{% csrf_token %}
	{{form.as_p}}
	<button>Submit</button>
</form>
{% endblock %}

templates/blogdelete.html
{% extends "base.html" %}
{% block content %}

<h3>Delete{{object.title}}?</h3>
<form method="POST">
	{% csrf_token %}
	<button>Sure</button>
	<a href="/blog/list">Cancel</a>
</form>

{% endblock %}

templates/blogdetail.html
{% extends "base.html" %}
{% block content %}

<a href="/blog/list/"><button>Back</button></a><hr>
<h3>{{blogobject.title}}<button><a href="/blog/{{blogobject.id}}/delete/">Delete</a></button></h3>
<p>{{blogobject.description}}</p>
<p>{{blogobject.author}}</p>



{% endblock %}

templates/bottle.html
{% extends "base.html" %}
{% block content %}
<h2>All Bottles</h2>
<a href="/bottle/add/">CreateBottle</a><hr>
{% for i in allbottles %}
<li>{{i.bottle_type}}</li>
<p>{{i.color}}</p>
<p>{{i.company}}</p>
{% endfor %}
{% endblock %}

templates/bottlecreate.html
{% extends "base.html" %}
{% block content %}


<h3>Bottle Form</h3><hr>
<form method="POST" action="">
	{% csrf_token %}
	{{form.as_p}}
	<button>Submit</button>
</form>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="row">
	
	<div class="col-md-4 mx-auto">
		<h3>All Task Assigned to: {{request.user}}</h3><hr>
		
		{% for us in request.user.task_set.all %}
		
			<li><a href="{% url 'taskapp:taskdetail' us.pk %}">{{us.title}}</a></li>
			

		
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
       	Login
		{% endblock %}


{% block content %}
<div class="row">
	<div class="col-md-4 mx-auto">
		<h3>
			<u><b>Login Form</b></u>
		</h3>
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info">Submit</button>
			<span class="text-danger">
				{{error}}
			</span>
			
		</form>
		
	</div>
	
</div>


{% endblock %}

templates/nepal.html
{% extends "base.html" %}
{% block content %}

<hr><h2>Nepal is beautiful</h2>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}
       	Signup
		{% endblock %}


{% block content %}
<div class="row">
	<div class="col-md-4 mx-auto">
		<h3>
			<u><b>SignUp Form</b></u>
		</h3>
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info">Submit</button>
			<b><span class="text-danger">
				{{error}}
			</span>
			</b>
		</form>
		
	</div>
	
</div>


{% endblock %}

templates/taskcreate.html
{% extends "base.html" %}
{% block content %}


<h3>Task Form</h3><hr>
<form method="POST" action="">
	{% csrf_token %}
	{{form.as_p}}
	<button>Submit</button>
</form>
{% endblock %}

templates/taskdelete.html
{% extends "base.html" %}
{% block content %}

<h3>Delete{{object.title}}?</h3>
<form method="POST">
	{% csrf_token %}
	<button>Sure</button>
	<a href="/task/list">Cancel</a>
</form>

{% endblock %}

templates/taskdetail.html
{% extends "base.html" %}




{% block content %}
<a href="/task/list/"><button>Back</button></a><hr>
<h3><u>{{taskobject.title}}
	<!-- <button><a href="/task/{{taskobject.id}}/delete/">Delete</a></button> -->
</u>
</h3>
<p>{{taskobject.description}}</p>
<h4>Due Date:{{taskobject.due_date}}</h4>


{% endblock %}

templates/tasks.html
{% extends "base.html" %}
{% block content %}
<h2>All Tasks</h2>
<a href="/task/add/">CreateTask</a>
<hr>
{% for i in alltasks %}

<b><li><a href="/task/{{i.id}}/detail/">{{i.title}}</a>(<a href="/task/{{i.id}}/update/">Update</a>)
</li></b>
<b><p>{{i.created_on}}</p></b>

{% endfor %}
{% endblock %}